Repository tambo-ai/tambo-cloud, pull requests merged in 2025-09, with the labels that each got.

#1657 feat: add docs MCP to mcp.tambo.co (TAM-214)
  .prettierignore
  apps/docs-mcp/.env.example
  apps/docs-mcp/.gitignore
  apps/docs-mcp/README.md
  apps/docs-mcp/app/global-error.tsx
  apps/docs-mcp/app/mcp/route.ts
  apps/docs-mcp/biome.json
  apps/docs-mcp/instrumentation-client.ts
  apps/docs-mcp/instrumentation.ts
  apps/docs-mcp/lib/analytics.ts
  apps/docs-mcp/lib/config.ts
  apps/docs-mcp/lib/constants.ts
  apps/docs-mcp/lib/handlers.ts
  apps/docs-mcp/lib/schemas.ts
  apps/docs-mcp/lib/types.ts
  apps/docs-mcp/next.config.ts
  apps/docs-mcp/package.json
  apps/docs-mcp/sentry.edge.config.ts
  apps/docs-mcp/sentry.server.config.ts
  apps/docs-mcp/tsconfig.json
  package-lock.json
  package.json
  packages/db/migrations/0071_pink_skrulls.sql
  packages/db/migrations/meta/0071_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/operations/index.ts
  packages/db/src/operations/mcp-usage.ts
  packages/db/src/schema.ts
  scripts/smoke-mcp.sh
  turbo.json
Labels: feat

#1689 fix(build): try upping target to 2023 to fix iterators?
  apps/api/tsconfig.json
Labels: fix

#1690 fix(iterators): add an await as an experiment
  packages/backend/src/services/llm/ai-sdk-client.ts
Labels: fix

#1688 chore(main): release repo 0.104.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1685 refactor(decision-loop): Consolidate tool-limit logic
  apps/api/src/threads/threads.service.ts
  apps/api/src/threads/util/tool-call-tracking.ts
Labels: refactor

#1694 chore(tools): Create a simple tool for doing SSE debugging
  package.json
  scripts/debug-stream.ts
Labels: chore

#1697 refactor(agents): A bunch of minor code improvements found during agent work
  apps/api/jest.config.ts
  apps/api/src/test/jest.setup.ts
  apps/api/src/threads/threads.service.ts
  apps/api/src/threads/util/__tests__/thread-state.spec.ts
  apps/api/src/threads/util/messages.ts
  apps/api/src/threads/util/thread-state.ts
  apps/web/app/(authed)/internal/smoketest/components/thread-message-input.tsx
  package.json
  packages/backend/src/services/decision-loop/decision-loop-service.ts
  packages/backend/src/services/llm/ai-sdk-client.ts
  packages/backend/src/util/template.ts
  packages/backend/tsconfig.json
Labels: refactor

#1693 chore(main): release repo 0.104.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1701 feat(agents): Agents support without mastra
  .prettierignore
  apps/api/package.json
  apps/api/src/projects/dto/project-response.dto.ts
  apps/api/src/projects/projects.service.ts
  apps/api/src/threads/__tests__/threads.service.spec.ts
  apps/api/src/threads/threads.service.ts
  apps/api/src/threads/util/thread-state.ts
  apps/web/package.json
  package-lock.json
  packages/backend/package.json
  packages/backend/src/index.ts
  packages/backend/src/services/decision-loop/agent-loop.ts
  packages/backend/src/services/llm/agent-client.ts
  packages/backend/src/services/llm/async-adapters.ts
  packages/backend/src/tambo-backend.ts
Labels: feat

#1698 chore(onboarding): add analytics template to onboarding wizard
  apps/web/components/dashboard-components/onboarding-wizard.tsx
Labels: chore

#1669 feat: add useTamboComponentState back into landing demo component
  apps/web/components/ui/tambo/founder-email-component.tsx
  package-lock.json
Labels: feat

#1729 feat: convert image part correctly to ai sdk format
  packages/backend/src/services/llm/ai-sdk-client.ts
Labels: feat

#1768 chore(code): remove a little more dead code
  apps/web/components/sections/logos.tsx
  apps/web/components/ui/border-number.tsx
  apps/web/components/ui/flickering-grid.tsx
  apps/web/components/ui/marquee.tsx
  apps/web/components/ui/navigation-menu.tsx
  apps/web/components/ui/orbiting-circles.tsx
Labels: chore

#1744 feat: enable custom llm parameters
  apps/api/src/projects/dto/project-response.dto.ts
  apps/api/src/projects/projects.service.ts
  apps/api/src/threads/threads.service.ts
  apps/web/components/dashboard-components/project-details/custom-llm-parameters-editor.tsx
  apps/web/components/dashboard-components/project-details/provider-key-section.tsx
  apps/web/lib/llm-parameters.ts
  apps/web/server/api/routers/project.ts
  packages/backend/src/services/llm/ai-sdk-client.ts
  packages/backend/src/tambo-backend.ts
  packages/core/src/index.ts
  packages/core/src/llm-parameter-types.ts
  packages/db/migrations/0073_brown_alex_power.sql
  packages/db/migrations/meta/0073_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/operations/project.ts
  packages/db/src/schema.ts
  packages/testing/src/factories.ts
Labels: feat

#1788 chore(lint): Disallow nested ternaries
  apps/api/src/threads/util/tool.ts
  apps/web/eslint.config.mjs
  package-lock.json
  packages/core/src/MCPClient.ts
  packages/db/package.json
  packages/db/src/operations/thread.ts
  packages/eslint-config/base.mjs
Labels: chore

#1787 chore(deps): bump to @tambo-ai/react@0.53 to pick up new sdk
  apps/web/package.json
  package-lock.json
Labels: chore
