Repository tambo-ai/tambo-cloud, pull requests merged in 2025-08, with the labels that each got.

#1525 fix: update docker setup to no longer require node
  DOCKER_README.md
  apps/api/Dockerfile
  apps/web/Dockerfile
  scripts/init-database.sh
  scripts/tambo-psql.sh
  scripts/tambo-setup.sh
  scripts/update-supabase.sh
Labels: fix

#1526 feat: add 'add tambo mcp to ide' button on homepage
  apps/web/components/sections/add-to-ide-dropdown.tsx
  apps/web/components/sections/hero.tsx
  apps/web/public/assets/landing/inkeep-gray-monochrome.svg
  turbo.json
Labels: feat

#1524 feat: add TamboHackBanner into dashboard header and main page layout
  apps/web/app/(redirects)/hack/page.tsx
  apps/web/app/login/LoginPage.tsx
  apps/web/app/page.tsx
  apps/web/components/sections/dashboard-header.tsx
  apps/web/components/sections/tambohack-banner.tsx
  apps/web/lib/env.ts
Labels: feat

#1529 fix: add project setting to require bearer token
  apps/api/src/projects/dto/project-response.dto.ts
  apps/api/src/projects/entities/project.entity.ts
  apps/api/src/projects/guards/__tests__/bearer-token.guard.spec.ts
  apps/api/src/projects/guards/bearer-token.guard.ts
  apps/api/src/projects/projects.service.ts
  apps/web/components/dashboard-components/project-details/oauth-settings.tsx
  apps/web/components/dashboard-components/project-details/project-info.tsx
  apps/web/components/dashboard-components/project-table.tsx
  apps/web/components/ui/switch.tsx
  apps/web/components/ui/tambo/chatwithtambo/tools.ts
  apps/web/server/api/routers/project.ts
  packages/db/migrations/0065_nifty_victor_mancha.sql
  packages/db/migrations/meta/0065_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/operations/project.ts
  packages/db/src/schema.ts
Labels: fix

#1506 feat(sentry): integrate Sentry for error tracking and performance monitoring
  apps/api/.env.example
  apps/api/package.json
  apps/api/src/app.controller.ts
  apps/api/src/common/filters/sentry-exception.filter.ts
  apps/api/src/main.ts
  apps/api/src/sentry.ts
  apps/api/src/threads/threads.service.ts
  apps/web/.env.example
  apps/web/app/global-error.tsx
  apps/web/instrumentation-client.ts
  apps/web/instrumentation.ts
  apps/web/lib/env.ts
  apps/web/next.config.mjs
  apps/web/package.json
  apps/web/sentry.edge.config.ts
  apps/web/sentry.server.config.ts
  apps/web/server/api/trpc.ts
  docker-compose.yml
  docker.env.example
  package-lock.json
  turbo.json
Labels: feat

#1530 fix: update openai SDK and deal with new "custom functions" type fallout
  apps/api/src/common/systemTools.ts
  apps/api/src/threads/threads.service.ts
  apps/api/src/threads/util/messages.ts
  apps/api/src/threads/util/thread-state.ts
  package-lock.json
  packages/backend/src/prompt/component-formatting.ts
  packages/backend/src/services/decision-loop/decision-loop-service.ts
  packages/backend/src/services/llm/ai-sdk-client.ts
  packages/backend/src/services/llm/llm-client.ts
  packages/backend/src/services/suggestion/suggestion.service.ts
  packages/backend/src/services/thread-name/thread-name.service.ts
  packages/backend/src/services/tool/tool-service.ts
  packages/core/package.json
  packages/core/src/strictness/tool-call-strict.ts
  packages/core/src/threads.ts
  packages/core/src/tools.ts
  packages/db/package.json
  packages/db/src/operations/messages.ts
  packages/db/src/operations/thread.ts
  packages/db/src/schema.ts
Labels: fix

#1531 chore(main): release repo 0.100.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1546 chore(deps): group all the sentry stuff together
  .github/dependabot.yml
Labels: chore

#1551 chore(hero): update hero title to what we had before
  apps/web/components/sections/hero.tsx
Labels: chore

#1550 docs: add init architecture diagram
  README.md
  assets/tambo-cloud-architecture.drawio.svg
Labels: docs

#1565 chore(main): release repo 0.100.6
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1567 chore(deps): remove libretto dependency
  package-lock.json
  packages/backend/package.json
  packages/backend/src/services/decision-loop/decision-loop-service.ts
  packages/backend/src/services/llm/ai-sdk-client.ts
  packages/backend/src/util/template.ts
Labels: chore

#1569 fix(sentry): customize Sentry integrations to exclude default Http integration and adjust request body size handling
  apps/api/src/sentry.ts
Labels: fix

#1570 fix: ignore context key in advance for thread
  apps/api/src/common/utils/extract-context-info.ts
  apps/api/src/threads/__tests__/threads.controller.integration.spec.ts
  apps/api/src/threads/__tests__/threads.controller.spec.ts
  apps/api/src/threads/threads.controller.ts
  apps/api/src/threads/threads.service.ts
Labels: fix

#1571 chore(main): release repo 0.100.8
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1572 fix(revert): Revert "fix: ignore context key in advance for thread"
  apps/api/src/common/utils/extract-context-info.ts
  apps/api/src/threads/__tests__/threads.controller.integration.spec.ts
  apps/api/src/threads/__tests__/threads.controller.spec.ts
  apps/api/src/threads/threads.controller.ts
  apps/api/src/threads/threads.service.ts
Labels: fix

#1574 fix(security): Do not leak contextKey out through our APIs
  apps/api/src/common/utils/oauth.ts
  apps/api/src/threads/dto/thread.dto.ts
  apps/api/src/threads/guards/thread-in-project-guard.ts
  apps/api/src/threads/threads.controller.ts
  apps/api/src/threads/threads.module.ts
  apps/api/src/threads/threads.service.ts
  packages/db/src/operations/thread.ts
Labels: fix

#1573 chore(main): release repo 0.100.9
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1577 chore(main): release repo 0.100.10
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1578 feat(webhooks): add authentication for signup webhook
  apps/api/src/users/users.controller.ts
  packages/db/src/operations/tambo-user.ts
  turbo.json
Labels: feat

#1596 chore(main): release repo 0.101.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1600 fix(cancellation): get rid of unawaited verification task, made transactions non-deterministic
  apps/api/src/threads/threads.service.ts
  packages/backend/src/util/thread-message-conversion.ts
Labels: fix

#1597 chore: update seo metadata
  apps/web/lib/config.tsx
Labels: chore

#1603 chore(observability): monitor SQL calls with sentry
  apps/api/src/sentry.ts
  apps/web/sentry.server.config.ts
Labels: chore

#1606 chore(observability): Allow setting sentry environment by env var
  apps/api/src/sentry.ts
  apps/web/instrumentation-client.ts
  apps/web/sentry.edge.config.ts
  apps/web/sentry.server.config.ts
  turbo.json
Labels: chore

#1607 chore(observability): pull in different pg instrumentation, see if this works in nestjs
  apps/api/src/main.ts
  apps/api/src/sentry.ts
  package-lock.json
Labels: chore

#1604 chore(main): release repo 0.101.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1610 perf(db): Add missing indexes from supabases perf advisor
  packages/db/migrations/0068_shallow_puma.sql
  packages/db/migrations/meta/0068_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/schema.ts
Labels: perf

#1612 chore: bump tsconfig for more modern compiled code in the nestjs project
  apps/api/src/common/utils/oauth.ts
  apps/api/tsconfig.json
  packages/core/src/oauth.ts
Labels: chore

#1611 chore(main): release repo 0.101.4
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1629 chore: update tambohack banner and chatwithtambo to be responsive
  apps/web/components/sections/tambohack-banner.tsx
  apps/web/components/ui/tambo/message-thread-collapsible.tsx
Labels: chore

#1630 perf(db): remove support for projects' legacy_id, it isn't used and is slowing down our queries
  apps/api/src/common/services/scheduler.service.ts
  packages/db/migrations/0069_overjoyed_gauntlet.sql
  packages/db/migrations/meta/0069_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/operations/project.ts
  packages/db/src/schema.ts
Labels: perf

#1638 perf(db): Minor query improvements, span naming
  apps/api/src/oauth/oauth.controller.ts
  apps/api/src/threads/threads.service.ts
  apps/api/src/threads/util/messages.ts
  apps/web/app/(authed)/dashboard/[projectId]/page.tsx
  apps/web/server/api/routers/project.ts
  packages/db/src/operations/thread.ts
Labels: perf

#1637 chore(main): release repo 0.101.7
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1639 chore(deps): npm dedupe && npm audit fix to clean up packages before agent branch lands
  package-lock.json
Labels: chore

#1643 chore(ci): fix sentry release action to pull the branch too
  .github/workflows/release-please.yml
Labels: chore

#1645 chore(ci): add commit depth to let sentry find history
  .github/workflows/release-please.yml
Labels: chore

#1640 chore(main): release repo 0.101.8
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1651 chore: fix dashboard demo layout
  apps/web/components/ui/tambo/thread-container.tsx
Labels: chore

#1653 fix: tambohack banner closing issue
  apps/web/components/sections/tambohack-banner.tsx
Labels: fix

#1656 feat(agents): add types and db schema for agent support
  packages/core/src/ComponentDecision.ts
  packages/core/src/ai-providers.ts
  packages/core/src/index.ts
  packages/db/migrations/0070_real_white_tiger.sql
  packages/db/migrations/meta/0070_snapshot.json
  packages/db/migrations/meta/_journal.json
  packages/db/src/operations/project.ts
  packages/db/src/schema.ts
Labels: feat

#1659 fix: avoid prefetching errors
  apps/web/app/not-found.tsx
  apps/web/components/mobile-drawer.tsx
  apps/web/components/sections/header-actions.tsx
  apps/web/components/sections/installation-steps.tsx
  apps/web/components/sections/mobile-dashboard-navigation.tsx
  apps/web/components/sections/social-proof.tsx
  apps/web/components/sections/tambohack-banner.tsx
  apps/web/components/sections/testimonials.tsx
  apps/web/components/sections/user-profile-dropdown.tsx
  apps/web/components/ui/discord-link.tsx
  apps/web/components/ui/github-link.tsx
Labels: fix

#1658 chore(main): release repo 0.103.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore, autorelease: pending

#1664 fix(sentry): add nested options for llm.model, etc
  apps/api/src/threads/threads.service.ts
Labels: fix

#1668 docs: a few more hydra->tambo things I missed
  CONTRIBUTING.md
  devdocs/BLOG.md
  devdocs/NAMING_CONVENTIONS.md
Labels: docs
